version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/storelydb?user=storely_user&password=storely_password
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/static/uploads_products
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=storelydb
      - POSTGRES_USER=storely_user
      - POSTGRES_PASSWORD=storely_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U storely_user -d storelydb"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  uploads: