ktor:
    application:
        modules:
            - com.mati.ApplicationKt.module
    deployment:
        port: ${PORT:8080}
#postgres:
#  url: "jdbc:postgresql://localhost/default"
#  user: username
#  password: password